version: '3.1'

services:
  course-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_DATABASE: "til_course_db"
    ports:
      - "3306:3306"
    networks:
      - til-net
    volumes: 
      - ms_course_volume:/var/lib/mysql
  
  worker-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_DATABASE: "til_worker_db"
    ports:
      - "3307:3306"
    networks:
      - til-net
    volumes: 
      - ms_worker_volume:/var/lib/mysql
  
  class-room-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_DATABASE: "til_class_db"
    ports:
      - "3308:3306"
    networks:
      - til-net
    volumes: 
      - ms_class_volume:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - til-net

networks: 
  til-net:
    driver: bridge
volumes: 
  ms_course_volume:
  ms_worker_volume:
  ms_class_volume: